# Generated by Django 4.2.2 on 2023-06-26 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransportCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_information', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.CharField(choices=[('12:00 AM', '12:00 AM'), ('01:00 AM', '01:00 AM'), ('02:00 AM', '02:00 AM'), ('03:00 AM', '03:00 AM'), ('04:00 AM', '04:00 AM'), ('05:00 AM', '05:00 AM'), ('06:00 AM', '06:00 AM'), ('07:00 AM', '07:00 AM'), ('08:00 AM', '08:00 AM'), ('09:00 AM', '09:00 AM'), ('10:00 AM', '10:00 AM'), ('11:00 AM', '11:00 AM'), ('12:00 PM', '12:00 PM'), ('01:00 PM', '01:00 PM'), ('02:00 PM', '02:00 PM'), ('03:00 PM', '03:00 PM'), ('04:00 PM', '04:00 PM'), ('05:00 PM', '05:00 PM'), ('06:00 PM', '06:00 PM'), ('07:00 PM', '07:00 PM'), ('08:00 PM', '08:00 PM'), ('09:00 PM', '09:00 PM'), ('10:00 PM', '10:00 PM'), ('11:00 PM', '11:00 PM')], max_length=10)),
                ('departure_time', models.CharField(choices=[('12:00 AM', '12:00 AM'), ('01:00 AM', '01:00 AM'), ('02:00 AM', '02:00 AM'), ('03:00 AM', '03:00 AM'), ('04:00 AM', '04:00 AM'), ('05:00 AM', '05:00 AM'), ('06:00 AM', '06:00 AM'), ('07:00 AM', '07:00 AM'), ('08:00 AM', '08:00 AM'), ('09:00 AM', '09:00 AM'), ('10:00 AM', '10:00 AM'), ('11:00 AM', '11:00 AM'), ('12:00 PM', '12:00 PM'), ('01:00 PM', '01:00 PM'), ('02:00 PM', '02:00 PM'), ('03:00 PM', '03:00 PM'), ('04:00 PM', '04:00 PM'), ('05:00 PM', '05:00 PM'), ('06:00 PM', '06:00 PM'), ('07:00 PM', '07:00 PM'), ('08:00 PM', '08:00 PM'), ('09:00 PM', '09:00 PM'), ('10:00 PM', '10:00 PM'), ('11:00 PM', '11:00 PM')], max_length=10)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_enquiry.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_enquiry.route')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_enquiry.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_enquiry.stop')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='destination_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_routes', to='bus_enquiry.stop'),
        ),
        migrations.AddField(
            model_name='route',
            name='starting_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_routes', to='bus_enquiry.stop'),
        ),
        migrations.AddField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(through='bus_enquiry.RouteStop', to='bus_enquiry.stop'),
        ),
        migrations.AddField(
            model_name='bus',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_enquiry.transportcompany'),
        ),
    ]
